"""API key management — centralized cadre.env operations."""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import dotenv_values, load_dotenv, set_key, unset_key

ENV_FILE = "cadre.env"

# Provider → environment variable mapping (single source of truth)
PROVIDER_ENV_VARS = {
    "anthropic": "ANTHROPIC_API_KEY",
    "openai": "OPENAI_API_KEY",
    "google": "GOOGLE_API_KEY",
    "deepseek": "DEEPSEEK_API_KEY",
}

# Provider → API key dashboard URLs
PROVIDER_DASHBOARDS = {
    "anthropic": "https://console.anthropic.com/settings/keys",
    "openai": "https://platform.openai.com/api-keys",
    "google": "https://aistudio.google.com/apikey",
    "deepseek": "https://platform.deepseek.com/api_keys",
}


def get_env_path(base_path: Path | None = None) -> Path:
    """Return the cadre.env file path for the project root."""
    if base_path is None:
        base_path = Path.cwd()
    return base_path / ENV_FILE


def load_env(base_path: Path | None = None) -> None:
    """Load cadre.env into os.environ. Does not override existing env vars."""
    env_path = get_env_path(base_path)
    if env_path.exists():
        load_dotenv(env_path, override=False)


def generate_env_file(
    base_path: Path | None = None,
    keys: dict[str, str] | None = None,
) -> Path:
    """Create cadre.env with provided keys and commented placeholders for the rest.

    Args:
        base_path: Project root directory.
        keys: Dict of provider_name → api_key_value for keys to write.

    Returns:
        Path to the created cadre.env file.
    """
    env_path = get_env_path(base_path)
    keys = keys or {}

    lines = [
        "# OpenCadre API Keys",
        "# This file is auto-generated by `cadre init`. Keep it out of version control.",
        "# Manage keys with: cadre keys set <provider>",
        "",
    ]

    for provider, env_var in PROVIDER_ENV_VARS.items():
        if keys.get(provider):
            lines.append(f"{env_var}={keys[provider]}")
        else:
            lines.append(f"# {env_var}=")

    lines.append("")
    env_path.write_text("\n".join(lines))
    return env_path


def key_set(base_path: Path | None = None, *, provider: str, value: str) -> None:
    """Set an API key in cadre.env for a provider.

    Creates cadre.env if it doesn't exist. Also sets in os.environ for immediate use.
    """
    env_path = get_env_path(base_path)
    if not env_path.exists():
        generate_env_file(base_path)

    env_var = PROVIDER_ENV_VARS.get(provider)
    if env_var is None:
        # Support arbitrary provider names
        env_var = f"{provider.upper()}_API_KEY"

    set_key(str(env_path), env_var, value)
    os.environ[env_var] = value


def key_remove(base_path: Path | None = None, *, provider: str) -> None:
    """Remove an API key from cadre.env."""
    env_path = get_env_path(base_path)
    if not env_path.exists():
        return

    env_var = PROVIDER_ENV_VARS.get(provider, f"{provider.upper()}_API_KEY")
    unset_key(str(env_path), env_var)
    os.environ.pop(env_var, None)


def show_keys(base_path: Path | None = None) -> dict[str, str | None]:
    """Read cadre.env and return provider → masked_key (or None if missing).

    Also checks os.environ for keys not in cadre.env.
    """
    env_path = get_env_path(base_path)
    file_values = dotenv_values(str(env_path)) if env_path.exists() else {}

    result: dict[str, str | None] = {}
    for provider, env_var in PROVIDER_ENV_VARS.items():
        raw = file_values.get(env_var) or os.environ.get(env_var)
        if raw:
            result[provider] = _mask_key(raw)
        else:
            result[provider] = None
    return result


def get_provider_for_model(model_string: str) -> str | None:
    """Extract provider name from a model string like 'anthropic/claude-sonnet-4-6'.

    Returns None if no slash separator found.
    """
    if "/" in model_string:
        return model_string.split("/", 1)[0]
    return None


def check_key_for_model(model_string: str, base_path: Path | None = None) -> bool:
    """Check if the provider for a given model has an API key configured."""
    provider = get_provider_for_model(model_string)
    if provider is None:
        return True  # Can't determine provider, assume OK

    # Ollama doesn't need API keys
    if provider == "ollama":
        return True

    env_var = PROVIDER_ENV_VARS.get(provider, f"{provider.upper()}_API_KEY")
    if os.environ.get(env_var):
        return True

    # Check cadre.env file
    env_path = get_env_path(base_path)
    if env_path.exists():
        values = dotenv_values(str(env_path))
        if values.get(env_var):
            return True

    return False


def _mask_key(key: str) -> str:
    """Mask an API key for display: show first 4 and last 4 chars."""
    if len(key) <= 8:
        return "****"
    return key[:4] + "..." + key[-4:]
